// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToTienDung0300567.DbContexts;

#nullable disable

namespace ToTienDung0300567.Migrations
{
    [DbContext(typeof(AppDbContexts0300567De21026))]
    [Migration("20250519035722_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToTienDung0300567.Entities.Mechanic0300567De20945", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("maTho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ngayNhanViec")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenTho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("cCCD")
                        .IsUnique();

                    b.HasIndex("maTho")
                        .IsUnique();

                    b.HasIndex("tenTho")
                        .IsUnique();

                    b.ToTable("Mechanic");
                });

            modelBuilder.Entity("ToTienDung0300567.Entities.RepairRecord0300567De20952", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("mechanicId")
                        .HasColumnType("int");

                    b.Property<int>("soLanSua")
                        .HasColumnType("int");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("mechanicId");

                    b.HasIndex("vehicleId");

                    b.ToTable("RepairRecord");
                });

            modelBuilder.Entity("ToTienDung0300567.Entities.Vehicle0300567De20949", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("bienSoXe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("loaiXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("bienSoXe")
                        .IsUnique();

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("ToTienDung0300567.Entities.RepairRecord0300567De20952", b =>
                {
                    b.HasOne("ToTienDung0300567.Entities.Mechanic0300567De20945", "mechanic")
                        .WithMany("RepairRecords")
                        .HasForeignKey("mechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToTienDung0300567.Entities.Vehicle0300567De20949", "vehicle")
                        .WithMany("RepairRecords")
                        .HasForeignKey("vehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mechanic");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("ToTienDung0300567.Entities.Mechanic0300567De20945", b =>
                {
                    b.Navigation("RepairRecords");
                });

            modelBuilder.Entity("ToTienDung0300567.Entities.Vehicle0300567De20949", b =>
                {
                    b.Navigation("RepairRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
